# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
@marlane = Descendent.create(first_name: "Marlane", last_name: "Porter", married: true, grandchildren: true, allergies: false, languages: 1)
@don = Descendent.create(first_name: "Don", last_name: "Porter", married: true, grandchildren: true, allergies: false, languages: 2)
@aaron = Descendent.create(first_name: "Aaron", last_name: "Porter", married: true, grandchildren: true, allergies: true, languages: 1, parent_id: @don.id)
@amy = Descendent.create(first_name: "Amy", last_name: "Finder", birthday:"06/09/1988", married: true, allergies: false, languages: 1, parent_id: @don.id)
@alissa = Descendent.create(first_name: "Alissa", last_name: "Lines", birthday:"06/09/1988", married: true, grandchildren: true, allergies: true, languages: 1, parent_id: @don.id)
@dana = Descendent.create(first_name: "Dana", last_name: "Burnett", birthday:"06/09/1988", married: true, grandchildren: true, allergies: false, languages: 2, parent_id: @don.id)
@justin = Descendent.create(first_name: "Justin", last_name: "Porter", birthday:"06/09/1988", married: true, allergies: false, languages: 1, parent_id: @don.id)
@lee = Descendent.create(first_name: "Lee", last_name: "Porter", birthday:"06/09/1988", married: true, allergies: false, languages: 2, parent_id: @don.id)
@rusty = Descendent.create(first_name: "Rusty", last_name: "Porter", birthday:"06/09/1988", married: true, allergies: false, languages: 3, parent_id: @don.id)
@rayden = Descendent.create(first_name: "Rayden", last_name: "Porter", birthday: "09/08/1995", married: false, allergies: true, languages: 2, parent_id: @aaron.id)
@rylee = Descendent.create(first_name: "Rylee", last_name: "Porter", birthday: "09/08/1995", married: true, allergies: true, languages: 1, parent_id: @aaron.id)
@morgan = Descendent.create(first_name: "Morgan", last_name: "Porter", birthday: "09/08/1995", married: false, allergies: true, languages: 1, parent_id: @aaron.id)
@halee = Descendent.create(first_name: "Halee", last_name: "Porter", birthday: "09/08/1995", married: false, allergies: false, languages: 2, parent_id: @aaron.id)
@brett = Descendent.create(first_name: "Brett", last_name: "Porter", birthday: "09/08/1995", married: false, allergies: true, languages: 1, parent_id: @aaron.id)
@logan = Descendent.create(first_name: "Logan", last_name: "Porter", birthday: "09/08/1995", married: false, allergies: false, languages: 2, parent_id: @aaron.id)
@rome= @rusty.missions.create(mission_name:"Rome", mission_language: "Italian", country: "Italy", members_baptized: 1, foreign_mission: true)
@pennsylvania = @aaron.missions.create(mission_name: "Pennyslvania", mission_language: "English", country: "United States", members_baptized: 10, foreign_mission: false)
@oaklahoma = @justin.missions.create(mission_name:"Tulsa, Oklahoma", mission_language: "English", country: "United States", members_baptized: 5, foreign_mission: false)
@brazil = @lee.missions.create(mission_name:"Riberão Preto", mission_language: "Portugese", country: "Brazil", members_baptized: 7, foreign_mission: true)
@spain = @aaron.missions.create(mission_name:"Madrid Spain", mission_language: "Spanish", country: "Spain", members_baptized: 11, foreign_mission: true)
@japan = @rayden.missions.create(mission_name: "Tokyo, Japan", mission_language: "Japanese", country: "Japan", members_baptized: 3, foreign_mission: true)
@tennessee = @rylee.missions.create(mission_name: "Tenessee", mission_language: "English", country: "United States", members_baptized: 3, foreign_mission: false)
@milan= @halee.missions.create(mission_name:"Milan", mission_language: "Italian", country: "Italy", members_baptized: 1, foreign_mission: true)
@gilbert = @brett.missions.create(mission_name: "Gilbert", mission_language: "English", country: "United States", members_baptized: 0, foreign_mission: false)
@asuncion = @logan.missions.create(mission_name:"Asuncion", mission_language: "Spanish", country: "Paraguay", members_baptized: 4, foreign_mission: true)
