# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
@marlane = Descendent.create(first_name: "Marlane", last_name: "Porter", married: true, grandchildren: true, allergies: false, languages: 1)
@don = Descendent.create(first_name: "Don", last_name: "Porter", married: true, grandchildren: true, allergies: false, languages: 2)
@aaron = Descendent.create(first_name: "Aaron", last_name: "Porter", married: true, grandchildren: true, allergies: true, languages: 1)
@amy = Descendent.create(first_name: "Amy", last_name: "Finder", birthday:"06/09/1988", married: true, allergies: false, languages: 1)
@alissa = Descendent.create(first_name: "Alissa", last_name: "Lines", birthday:"06/09/1988", married: true, grandchildren: true, allergies: true, languages: 1)
@dana = Descendent.create(first_name: "Dana", last_name: "Burnett", birthday:"06/09/1988", married: true, grandchildren: true, allergies: false, languages: 2)
@justin = Descendent.create(first_name: "Justin", last_name: "Porter", birthday:"06/09/1988", married: true, allergies: false, languages: 1)
@lee = Descendent.create(first_name: "Lee", last_name: "Porter", birthday:"06/09/1988", married: true, allergies: false, languages: 2)
@rusty = Descendent.create(first_name: "Rusty", last_name: "Porter", birthday:"06/09/1988", married: true, allergies: false, languages: 3)
@morgan = Descendent.create(first_name: "Morgan", last_name: "Porter", birthday: "09/08/1995", married: false, allergies: true, languages: 1, parent_id: @aaron.id)
@rayden = Descendent.create(first_name: "Rayden", last_name: "Porter", birthday: "09/08/1995", married: false, allergies: true, languages: 2, parent_id: @aaron.id)
@rylee = Descendent.create(first_name: "Rylee", last_name: "Porter", birthday: "09/08/1995", married: true, allergies: true, languages: 1, parent_id: @aaron.id)
@halee = Descendent.create(first_name: "Halee", last_name: "Porter", birthday: "09/08/1995", married: false, allergies: false, languages: 2, parent_id: @aaron.id)
@brett = Descendent.create(first_name: "Brett", last_name: "Porter", birthday: "09/08/1995", married: false, allergies: true, languages: 1, parent_id: @aaron.id)
@logan = Descendent.create(first_name: "Logan", last_name: "Porter", birthday: "09/08/1995", married: false, allergies: false, languages: 2, parent_id: @aaron.id)
@hana = Descendent.create(first_name: "Hana", last_name: "Finder", birthday: "09/08/1995", married: false, allergies: false, languages: 1, parent_id: @amy.id)
@ethan = Descendent.create(first_name: "Ethan", last_name: "Finder", birthday: "09/08/1995", married: false, allergies: false, languages: 1, parent_id: @amy.id)
@oran = Descendent.create(first_name: "Oran", last_name: "Finder", birthday: "09/08/1995", married: false, allergies: false, languages: 1, parent_id: @amy.id)
@kael = Descendent.create(first_name: "Kael", last_name: "Finder", birthday: "09/08/1995", married: false, allergies: false, languages: 1, parent_id: @amy.id)
@jaci = Descendent.create(first_name: "Jaci", last_name: "Gillespie", birthday: "09/08/1995", married: true, allergies: true, languages: 1, parent_id: @alissa.id)
@cami = Descendent.create(first_name: "Cami", last_name: "Gillespie", birthday: "09/08/1995", married: true, allergies: true, languages: 1, parent_id: @alissa.id)
@brian = Descendent.create(first_name: "Brian", last_name: "Lines", birthday: "09/08/1995", married: false, allergies: true, languages: 2, parent_id: @alissa.id)
@allen = Descendent.create(first_name: "Allen", last_name: "Lines", birthday: "09/08/1995", married: false, allergies: true, languages: 1, parent_id: @alissa.id)
@caroyln = Descendent.create(first_name: "Carolyn", last_name: "Lines", birthday: "09/08/1995", married: false, allergies: true, languages: 1, parent_id: @alissa.id)
@robert = Descendent.create(first_name: "Robert", last_name: "Lines", birthday: "09/08/1995", married: false, allergies: true, languages: 1, parent_id: @alissa.id)
@tj = Descendent.create(first_name: "TJ", last_name: "Burnett", birthday: "09/08/1995", married: false, allergies: true, languages: 1, parent_id: @dana.id)
@natalie = Descendent.create(first_name: "Natalie", last_name: "Taylor", birthday: "09/08/1995", married: true, allergies: true, languages: 1, parent_id: @dana.id)
@elaina = Descendent.create(first_name: "Elaina", last_name: "Burnett", birthday: "09/08/1995", married: false, allergies: true, languages: 2, parent_id: @dana.id)
@tyler = Descendent.create(first_name: "Tyler", last_name: "Burnett", birthday: "09/08/1995", married: false, allergies: true, languages: 1, parent_id: @dana.id)
@lydia = Descendent.create(first_name: "Lydia", last_name: "Burnett", birthday: "09/08/1995", married: false, allergies: true, languages: 1, parent_id: @dana.id)
@zander = Descendent.create(first_name: "Zander", last_name: "Burnett", birthday: "09/08/1995", married: false, allergies: true, languages: 1, parent_id: @dana.id)
@maddie = Descendent.create(first_name: "Maddie", last_name: "Porter", birthday: "09/08/1995", married: false, allergies: true, languages: 1, parent_id: @justin.id)
@mckinlee = Descendent.create(first_name: "McKinlee", last_name: "Porter", birthday: "09/08/1995", married: false, allergies: true, languages: 1, parent_id: @justin.id)
@monroe = Descendent.create(first_name: "Monroe", last_name: "Porter", birthday: "09/08/1995", married: false, allergies: true, languages: 1, parent_id: @justin.id)
@millie = Descendent.create(first_name: "Millie", last_name: "Porter", birthday: "09/08/1995", married: false, allergies: true, languages: 1, parent_id: @justin.id)
@eden = Descendent.create(first_name: "Eden", last_name: "Porter", birthday: "09/08/1995", married: false, allergies: true, languages: 1, parent_id: @lee.id)
@delia = Descendent.create(first_name: "Delia", last_name: "Porter", birthday: "09/08/1995", married: false, allergies: true, languages: 1, parent_id: @lee.id)
@gwen = Descendent.create(first_name: "Gwen", last_name: "Porter", birthday: "09/08/1995", married: false, allergies: true, languages: 1, parent_id: @lee.id)
@emerson = Descendent.create(first_name: "Emerson", last_name: "Porter", birthday: "09/08/1995", married: false, allergies: true, languages: 1, parent_id: @lee.id)
@adeline = Descendent.create(first_name: "Adeline", last_name: "Porter", birthday: "08/11/2015", married: false, allergies: true, languages: 1, parent_id: @rusty.id)
@brielle = Descendent.create(first_name: "Brielle", last_name: "Porter", birthday: "09/08/2017", married: false, allergies: true, languages: 1, parent_id: @rusty.id)
@callum = Descendent.create(first_name: "Callum", last_name: "Porter", birthday: "04/20/2021", married: false, allergies: true, languages: 1, parent_id: @rusty.id)
@elliot = Descendent.create(first_name: "Elliot", last_name: "Porter", birthday: "04/20/2021", married: false, allergies: true, languages: 1, grandparent_id: @aaron.id)
@noah = Descendent.create(first_name: "Noah", last_name: "Porter", birthday: "04/20/2021", married: false, allergies: true, languages: 1, grandparent_id: @aaron.id)
@graham = Descendent.create(first_name: "Graham", last_name: "Gillespie", birthday: "04/20/2021", married: false, allergies: true, languages: 1, grandparent_id: @alissa.id)
@peyton = Descendent.create(first_name: "Peyton", last_name: "Taylor", birthday: "04/20/2021", married: false, allergies: true, languages: 1, grandparent_id: @dana.id)
@tatum = Descendent.create(first_name: "Tatum", last_name: "Taylor", birthday: "04/20/2021", married: false, allergies: true, languages: 1, grandparent_id: @dana.id)
@rome= @rusty.missions.create(mission_name:"Rome", mission_language: "Italian", country: "Italy", members_baptized: 1, foreign_mission: true)
@pennsylvania = @aaron.missions.create(mission_name: "Pennyslvania", mission_language: "English", country: "United States", members_baptized: 10, foreign_mission: false)
@oaklahoma = @justin.missions.create(mission_name:"Tulsa", mission_language: "English", country: "United States", members_baptized: 5, foreign_mission: false)
@brazil = @lee.missions.create(mission_name:"Riberão Preto", mission_language: "Portugese", country: "Brazil", members_baptized: 7, foreign_mission: true)
@spain = @aaron.missions.create(mission_name:"Madrid", mission_language: "Spanish", country: "Spain", members_baptized: 11, foreign_mission: true)
@japan = @rayden.missions.create(mission_name: "Tokyo", mission_language: "Japanese", country: "Japan", members_baptized: 3, foreign_mission: true)
@tennessee = @rylee.missions.create(mission_name: "Tenessee", mission_language: "English", country: "United States", members_baptized: 3, foreign_mission: false)
@milan= @halee.missions.create(mission_name:"Milan", mission_language: "Italian", country: "Italy", members_baptized: 1, foreign_mission: true)
@gilbert = @brett.missions.create(mission_name: "Gilbert", mission_language: "English", country: "United States", members_baptized: 0, foreign_mission: false)
@asuncion = @logan.missions.create(mission_name:"Asuncion", mission_language: "Spanish", country: "Paraguay", members_baptized: 4, foreign_mission: true)
@puebla = @elaina.missions.create(mission_name:"Puebla", mission_language: "Spanish", country: "Mexico", members_baptized: 4, foreign_mission: true)
@tijuana = @brian.missions.create(mission_name:"Tijuana", mission_language: "Spanish", country: "Mexico", members_baptized: 4, foreign_mission: true)
@anchorage = @allen.missions.create(mission_name:"Anchorage", mission_language: "English", country: "United States", members_baptized: 4, foreign_mission: false)
